CREATE TABLE user_table(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(15) NOT NULL,
last_name VARCHAR(15) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
login VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(20) NOT NULL,
role ENUM("Admin", "librarian", "Reader") NOT NULL
);
